# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: wget https://dist.ipfs.tech/kubo/v0.15.0/kubo_v0.15.0_linux-amd64.tar.gz && tar -xzf kubo_v0.15.0_linux-amd64.tar.gz && cd kubo && sudo bash install.sh
    - run: ipfs --version
    - run: ipfs add -r ./dist --api /ip4/3.112.126.56/tcp/5001 > ipfs.txt
    - run: cat ipfs.txt
    - run: node .github/scripts/make-final-link.js ipfs.txt ipfs.md
    - run: node .github/scripts/update.readme.js ipfs.txt
    - run: cat README.md
    - run: mv dist w3-poc && tar cvf w3-poc.tar.gz w3-poc
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          w3-poc.tar.gz
          ipfs.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      commit-message: "update readme.md - latest ipfs address"
